/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 04-dic.-2025 5:28:27 p. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */





















/* Drop Tables */

DROP TABLE IF EXISTS admins CASCADE
;

DROP TABLE IF EXISTS bicycle CASCADE
;

DROP TABLE IF EXISTS city CASCADE
;

DROP TABLE IF EXISTS complaints_and_claims CASCADE
;

DROP TABLE IF EXISTS fine CASCADE
;

DROP TABLE IF EXISTS maintenance CASCADE
;

DROP TABLE IF EXISTS panic_button CASCADE
;

DROP TABLE IF EXISTS slots CASCADE
;

DROP TABLE IF EXISTS station CASCADE
;

DROP TABLE IF EXISTS travel CASCADE
;

DROP TABLE IF EXISTS user_fine CASCADE
;

DROP TABLE IF EXISTS users CASCADE
;

/* Create Tables */

CREATE TABLE admins
(
	k_uid_admin varchar(100) NOT NULL,	-- Llave primaria de admins(Administradores) que entrega el servidor de autenticacion.
	n_admin_name varchar(50) NOT NULL	-- Primer nombre del usuario.
)
;

CREATE TABLE bicycle
(
	k_id_bicycle varchar(11) NOT NULL,	-- Llave primaria de la bicicleta.
	k_series integer NOT NULL,	-- Serie de la bicicleta.
	n_model varchar(50) NOT NULL,	-- Modelo de la bicicleta.
	t_padlock_status varchar(50) NOT NULL   DEFAULT 'LOCKED',	-- Estado del candado de la bicicleta.
	f_last_update timestamp without time zone NULL,	-- Ultima actualizacion de la bicicleta.
	n_latitude double precision NULL,	-- Latitud de la posicion de la bicicleta.
	n_length double precision NULL,	-- Longitud de la posicion de la bicicleta.
	v_battery numeric(5,2) NULL	-- Bateria de la bicicleta.
)
;

CREATE TABLE city
(
	k_id_city serial NOT NULL,	-- Llave primaria de la ciudad.
	n_city_name varchar(50) NULL	-- Nombre de la ciudad.
)
;

CREATE TABLE complaints_and_claims
(
	k_id_complaints_and_claims serial NOT NULL,	-- Llave primaria de quejas y reclamos.
	d_description varchar(500) NOT NULL,	-- Descripcion de la queja o reclamos que se presento.
	t_status varchar(50) NOT NULL,	-- Estado de la queja o reclamo que se solicito.
	k_id_travel serial NOT NULL,	-- Llave foranea que viena desde viaje.
	t_type varchar(50) NOT NULL
)
;

CREATE TABLE fine
(
	k_id_fine serial NOT NULL,	-- Llave primaria de fine.
	v_amount integer NOT NULL,	-- Valor de las multas.
	d_description varchar(250) NOT NULL	-- Descripcion de la multa.
)
;

CREATE TABLE maintenance
(
	k_id_maintenance varchar(50) NOT NULL,	-- Identificador único del registro de mantenimiento. Actúa como clave primaria de la tabla y permite distinguir cada intervención realizada sobre una bicicleta, asegurando integridad y trazabilidad en el historial técnico. Su unicidad garantiza que cada mantenimiento pueda auditarse, referenciarse y consultarse de manera independiente en el sistema.
	d_description varchar(250) NOT NULL,	-- Contiene el detalle del mantenimiento realizado, incluyendo el tipo de actividad ejecutada (correctivo, preventivo, inspección, cambio de partes, etc.). Permite documentar las acciones aplicadas sobre la bicicleta para futuras referencias, auditoría y control interno.
	t_status varchar(50) NOT NULL,	-- Indica el estado del mantenimiento registrado. Puede reflejar etapas como pendiente, en proceso, completado, según el flujo definido por la operación. Facilita la gestión del ciclo de mantenimiento y permite identificar trabajos abiertos o finalizados.
	f_date date NOT NULL,	-- Registra la fecha en la que se realizó o programó el mantenimiento. Permite ordenar cronológicamente el historial de intervenciones y evaluar la frecuencia de reparaciones o servicios preventivos aplicados a cada bicicleta.
	k_id_bicycle varchar(11) NULL,	-- Identificador único de la bicicleta a la que se le realizó el mantenimiento. Este valor hace referencia directa a la bicicleta registrada en el sistema y permite asociar cada intervención con un elemento físico específico de la flota. Al ser de tipo VARCHAR, admite codificación que diferencia bicicletas eléctricas y mecánicas, mejorando el control operativo y la trazabilidad del historial técnico.
	t_entity_type varchar(50) NOT NULL,
	t_maintenance_type varchar(50) NOT NULL,
	t_triggered_by varchar(50) NOT NULL,
	v_cost integer NULL,
	k_id_slot varchar(50) NULL,
	k_id_station integer NULL
)
;

CREATE TABLE panic_button
(
	k_id_panic_button serial NOT NULL,
	f_activation_date timestamp without time zone NOT NULL,
	k_id_station integer NOT NULL
)
;

CREATE TABLE slots
(
	k_id_slot varchar(50) NOT NULL,	-- Identificador único del slot dentro del sistema. Es la llave primaria de la tabla y permite distinguir de manera inequívoca cada punto de anclaje disponible en una estación.
	t_padlock_status varchar(50) NOT NULL   DEFAULT 'UNLOCKED',	-- Indica el estado actual del candado electrónico asociado al slot. Usualmente representa valores como abierto, cerrado, bloqueado, fallo, entre otros. Es un campo clave para determinar si un slot está disponible para recibir una bicicleta o si requiere mantenimiento.
	k_id_station integer NOT NULL,	-- Llave foránea que referencia a la estación a la que pertenece el slot. Permite relacionar cada punto de anclaje con una ubicación física específica dentro del sistema de estaciones.
	k_id_bicycle varchar(11) NULL
)
;

CREATE TABLE station
(
	k_id_station serial NOT NULL,	-- Llave primaria de la estacion.
	n_station_name varchar(50) NOT NULL,	-- Nombre de la estacion.
	n_latitude double precision NOT NULL,	-- Latitud de la ubicacion exacta de la estacion.
	n_length double precision NOT NULL,	-- Longitud de la ubicacion exacta de la estacion.
	k_id_city integer NOT NULL,	-- Llave foranea que vien desde ciudad.
	t_type varchar(50) NOT NULL,
	t_cctv_status boolean NOT NULL   DEFAULT true	-- Es el campo encargado de dar verificacion si el CCTV esta activo y funcional
)
;

CREATE TABLE travel
(
	k_id_travel serial NOT NULL,	-- Llave primaria del viaje.
	f_required_at timestamp without time zone NOT NULL   DEFAULT NOW(),	-- Entidad encargada de guardar la fecha de solitud de viaje.
	f_started_at timestamp without time zone NULL,	-- Fecha de inicio del viaje.
	f_ended_at timestamp without time zone NULL,	-- Fecha de finalizacion del viaje
	t_status varchar(20) NOT NULL,	-- Estado del viaje
	k_id_bicycle varchar(11) NOT NULL,	-- Llave foranea de Bicycle
	k_from_id_station integer NOT NULL,	-- Llave foranea de la estacion de donde se inicio el viaje.
	k_to_id_station integer NULL,	-- Llave Foranea de la estacion en donde se termina el viaje
	k_uid_user varchar(100) NULL,
	t_travel_type varchar(50) NOT NULL,
	v_travel_cost numeric(5,2) NULL
)
;

CREATE TABLE user_fine
(
	k_user_fine serial NOT NULL,	-- Llave primaria de la tabla de rompimiento entre user y fine.
	n_reason varchar(250) NOT NULL,	-- Razon por la cual le pusieron la multa al usuario.
	t_state varchar(50) NOT NULL   DEFAULT 'PENDING',	-- Estado de la multa que se le puso al usuario.
	k_id_fine integer NOT NULL,	-- Llave foranea de fine(multa)
	k_uid_user varchar(100) NULL,	-- Llave foranea de user(usuario)
	v_amount_snapshot integer NULL,	-- Valor que tuvo la multa en el momento en que se la colocaron.
	f_assigned_at timestamp without time zone NOT NULL   DEFAULT NOW(),	-- Fecha en la que fue asignada la multa.
	f_update_at timestamp without time zone NULL	-- Fecha en la que fue actualizada la multa.
)
;

CREATE TABLE users
(
	k_uid_user varchar(100) NOT NULL,	-- Llave primaria de user(Usuarios) que entrega el servidor de autenticacion.
	n_user_name varchar(50) NOT NULL,	-- Primer nombre del usuario.
	n_user_email varchar(50) NOT NULL,
	t_subscription_type varchar(50) NOT NULL   DEFAULT 'NONE',	-- Tipo de suscripcion del usuario.
	v_balance numeric(5,2) NULL,	-- Saldo de los usuario
	t_subcripcion_travels integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE admins ADD CONSTRAINT "PK_admins"
	PRIMARY KEY (k_uid_admin)
;

ALTER TABLE bicycle ADD CONSTRAINT "PK_Bicycle"
	PRIMARY KEY (k_id_bicycle)
;

ALTER TABLE bicycle
  ADD CONSTRAINT "UNQ_k_series" UNIQUE (k_series)
;

ALTER TABLE bicycle ADD CONSTRAINT "CHK_v_battery" CHECK (v_battery BETWEEN 0 AND 100)
;

ALTER TABLE bicycle ADD CONSTRAINT "CHK_t_padlock_status" CHECK (t_padlock_status IN ('LOCKED', 'UNLOCKED', 'ERROR', 'MAINTENANCE', 'RESERVED'))
;

ALTER TABLE bicycle ADD CONSTRAINT "CHK_n_model" CHECK (n_model IN ('MECHANIC', 'ELECTRIC'))
;

ALTER TABLE city ADD CONSTRAINT "PK_city"
	PRIMARY KEY (k_id_city)
;

ALTER TABLE city
  ADD CONSTRAINT "UNQ_n_city_name" UNIQUE (n_city_name)
;

ALTER TABLE complaints_and_claims ADD CONSTRAINT "PK_complaints_and_claims"
	PRIMARY KEY (k_id_complaints_and_claims)
;

ALTER TABLE complaints_and_claims ADD CONSTRAINT "CHK_t_type" CHECK (t_type IN ('BICYCLE', 'SLOT', 'STATION'))
;

CREATE INDEX "IXFK_complaints_and_claims_travel" ON complaints_and_claims (k_id_travel ASC)
;

ALTER TABLE fine ADD CONSTRAINT "PK_Fine"
	PRIMARY KEY (k_id_fine)
;

ALTER TABLE maintenance ADD CONSTRAINT "PK_maintenance"
	PRIMARY KEY (k_id_maintenance)
;

ALTER TABLE maintenance ADD CONSTRAINT "CHK_t_status" CHECK (t_status IN ('PENDING', 'SOLVING', 'RESOLVED'))
;

ALTER TABLE maintenance ADD CONSTRAINT "CHK_t_entity_type" CHECK (t_entity_type IN ('BICYCLE', 'STATION', 'LOCK'))
;

ALTER TABLE maintenance ADD CONSTRAINT "CHK_t_maintenance_type" CHECK (t_maintenance_type IN ('PREVENTIVE', 'CORRECTIVE', 'INSPECTION'))
;

ALTER TABLE maintenance ADD CONSTRAINT "CHK_t_triggered_by" CHECK (t_triggered_by IN ('ADMIN', 'USER', 'IOT_ALERT'))
;

ALTER TABLE panic_button ADD CONSTRAINT "PK_panic_button"
	PRIMARY KEY (k_id_panic_button)
;

CREATE INDEX "IXFK_panic_button_station" ON panic_button (k_id_station ASC)
;

ALTER TABLE slots ADD CONSTRAINT "PK_Slots"
	PRIMARY KEY (k_id_slot)
;

ALTER TABLE slots
  ADD CONSTRAINT "UNQ_k_id_bicycle" UNIQUE (k_id_bicycle)
;

ALTER TABLE slots ADD CONSTRAINT "CHK_t_padlock_status" CHECK (t_padlock_status IN ('LOCKED', 'UNLOCKED', 'ERROR', 'MAINTENANCE', 'RESERVED'))
;

CREATE INDEX "IXFK_slots_bicycle" ON slots (k_id_bicycle ASC)
;

CREATE INDEX "IXFK_Slots_station" ON slots (k_id_station ASC)
;

ALTER TABLE station ADD CONSTRAINT "PK_Station"
	PRIMARY KEY (k_id_station)
;

ALTER TABLE station ADD CONSTRAINT "CK_Type" CHECK (t_type IN ('RESIDENTIAL', 'METRO', 'FINANCIAL CENTER'))
;

CREATE INDEX "IXFK_Station_City" ON station (k_id_city ASC)
;

ALTER TABLE travel ADD CONSTRAINT "PK_Travel"
	PRIMARY KEY (k_id_travel)
;

ALTER TABLE travel ADD CONSTRAINT "CK_Travel_status" CHECK (t_status IN ('IN_PROGRESS', 'COMPLETED'))
;

CREATE INDEX "IXFK_travel_bicycle" ON travel (k_id_bicycle ASC)
;

CREATE INDEX "IXFK_travel_station" ON travel (k_from_id_station ASC)
;

CREATE INDEX "IXFK_travel_station_02" ON travel (k_to_id_station ASC)
;

CREATE INDEX "IXFK_travel_users" ON travel (k_uid_user ASC)
;

ALTER TABLE user_fine ADD CONSTRAINT "PK_User_fine"
	PRIMARY KEY (k_user_fine)
;

ALTER TABLE user_fine ADD CONSTRAINT "CHK_t_state" CHECK (t_state IN ('PENDING', 'PAID'))
;

CREATE INDEX "IXFK_User_fine_Fine" ON user_fine (k_id_fine ASC)
;

CREATE INDEX "IXFK_user_fine_users" ON user_fine (k_uid_user ASC)
;

ALTER TABLE users ADD CONSTRAINT "PK_Users"
	PRIMARY KEY (k_uid_user)
;

ALTER TABLE users ADD CONSTRAINT "CHK_t_subscription_type" CHECK (t_subscription_type IN ('NONE', 'MONTHLY')
)
;

ALTER TABLE users ADD CONSTRAINT "CHK_t_subcripcion_travels" CHECK (t_subcripcion_travels BETWEEN 0 AND 150)
;

/* Create Foreign Key Constraints */

ALTER TABLE complaints_and_claims ADD CONSTRAINT "FK_complaints_and_claims_travel"
	FOREIGN KEY (k_id_travel) REFERENCES travel (k_id_travel) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE maintenance ADD CONSTRAINT "FK_maintenance_bicycle"
	FOREIGN KEY (k_id_bicycle) REFERENCES bicycle (k_id_bicycle) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE maintenance ADD CONSTRAINT "FK_maintenance_slots"
	FOREIGN KEY (k_id_slot) REFERENCES slots (k_id_slot) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE maintenance ADD CONSTRAINT "FK_maintenance_station"
	FOREIGN KEY (k_id_station) REFERENCES station (k_id_station) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE panic_button ADD CONSTRAINT "FK_panic_button_station"
	FOREIGN KEY (k_id_station) REFERENCES station (k_id_station) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE slots ADD CONSTRAINT "FK_slots_bicycle"
	FOREIGN KEY (k_id_bicycle) REFERENCES bicycle (k_id_bicycle) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE slots ADD CONSTRAINT "FK_Slots_station"
	FOREIGN KEY (k_id_station) REFERENCES station (k_id_station) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE station ADD CONSTRAINT "FK_Station_City"
	FOREIGN KEY (k_id_city) REFERENCES city (k_id_city) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE travel ADD CONSTRAINT "FK_travel_bicycle"
	FOREIGN KEY (k_id_bicycle) REFERENCES bicycle (k_id_bicycle) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE travel ADD CONSTRAINT "FK_travel_station"
	FOREIGN KEY (k_from_id_station) REFERENCES station (k_id_station) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE travel ADD CONSTRAINT "FK_travel_station_02"
	FOREIGN KEY (k_to_id_station) REFERENCES station (k_id_station) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE travel ADD CONSTRAINT "FK_travel_users"
	FOREIGN KEY (k_uid_user) REFERENCES users (k_uid_user) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE user_fine ADD CONSTRAINT "FK_User_fine_Fine"
	FOREIGN KEY (k_id_fine) REFERENCES fine (k_id_fine) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE user_fine ADD CONSTRAINT "FK_user_fine_users"
	FOREIGN KEY (k_uid_user) REFERENCES users (k_uid_user) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE admins
	IS 'Tabla que guarda todos los datos de los administradores
.'
;

COMMENT ON COLUMN admins.k_uid_admin
	IS 'Llave primaria de admins(Administradores) que entrega el servidor de autenticacion.'
;

COMMENT ON COLUMN admins.n_admin_name
	IS 'Primer nombre del usuario.'
;

COMMENT ON TABLE bicycle
	IS 'Esta es la tabla en la que se guardan los datos de las bicicletas.'
;

COMMENT ON COLUMN bicycle.k_id_bicycle
	IS 'Llave primaria de la bicicleta.'
;

COMMENT ON COLUMN bicycle.k_series
	IS 'Serie de la bicicleta.'
;

COMMENT ON COLUMN bicycle.n_model
	IS 'Modelo de la bicicleta.'
;

COMMENT ON COLUMN bicycle.t_padlock_status
	IS 'Estado del candado de la bicicleta.'
;

COMMENT ON COLUMN bicycle.f_last_update
	IS 'Ultima actualizacion de la bicicleta.'
;

COMMENT ON COLUMN bicycle.n_latitude
	IS 'Latitud de la posicion de la bicicleta.'
;

COMMENT ON COLUMN bicycle.n_length
	IS 'Longitud de la posicion de la bicicleta.'
;

COMMENT ON COLUMN bicycle.v_battery
	IS 'Bateria de la bicicleta.'
;

COMMENT ON TABLE city
	IS 'En esta tabla se van a guardar las ciudades.'
;

COMMENT ON COLUMN city.k_id_city
	IS 'Llave primaria de la ciudad.'
;

COMMENT ON COLUMN city.n_city_name
	IS 'Nombre de la ciudad.'
;



COMMENT ON TABLE complaints_and_claims
	IS 'Esta tabla se encarga de registrar todas las quejas y reclamos que puedan surgir durante el viaje. Su propósito es mantener un registro detallado de los incidentes reportados por los pasajeros, para su posterior análisis y resolución.'
;

COMMENT ON COLUMN complaints_and_claims.k_id_complaints_and_claims
	IS 'Llave primaria de quejas y reclamos.'
;

COMMENT ON COLUMN complaints_and_claims.d_description
	IS 'Descripcion de la queja o reclamos que se presento.'
;

COMMENT ON COLUMN complaints_and_claims.t_status
	IS 'Estado de la queja o reclamo que se solicito.'
;

COMMENT ON COLUMN complaints_and_claims.k_id_travel
	IS 'Llave foranea que viena desde viaje.'
;





COMMENT ON TABLE fine
	IS 'Es la tabla encargada de guardar las multas.'
;

COMMENT ON COLUMN fine.k_id_fine
	IS 'Llave primaria de fine.'
;

COMMENT ON COLUMN fine.v_amount
	IS 'Valor de las multas.'
;

COMMENT ON COLUMN fine.d_description
	IS 'Descripcion de la multa.'
;



COMMENT ON TABLE maintenance
	IS 'La tabla maintenance almacena el historial de mantenimientos realizados a cada bicicleta del sistema. Permite registrar intervenciones preventivas y correctivas, fechas de ejecución, estado del mantenimiento y observaciones asociadas. Su principal propósito es garantizar trazabilidad, control operativo y evaluación del estado mecánico o eléctrico de la flota.'
;

COMMENT ON COLUMN maintenance.k_id_maintenance
	IS 'Identificador único del registro de mantenimiento. Actúa como clave primaria de la tabla y permite distinguir cada intervención realizada sobre una bicicleta, asegurando integridad y trazabilidad en el historial técnico. Su unicidad garantiza que cada mantenimiento pueda auditarse, referenciarse y consultarse de manera independiente en el sistema.'
;

COMMENT ON COLUMN maintenance.d_description
	IS 'Contiene el detalle del mantenimiento realizado, incluyendo el tipo de actividad ejecutada (correctivo, preventivo, inspección, cambio de partes, etc.). Permite documentar las acciones aplicadas sobre la bicicleta para futuras referencias, auditoría y control interno.'
;

COMMENT ON COLUMN maintenance.t_status
	IS 'Indica el estado del mantenimiento registrado. Puede reflejar etapas como pendiente, en proceso, completado, según el flujo definido por la operación. Facilita la gestión del ciclo de mantenimiento y permite identificar trabajos abiertos o finalizados.'
;

COMMENT ON COLUMN maintenance.f_date
	IS 'Registra la fecha en la que se realizó o programó el mantenimiento. Permite ordenar cronológicamente el historial de intervenciones y evaluar la frecuencia de reparaciones o servicios preventivos aplicados a cada bicicleta.'
;

COMMENT ON COLUMN maintenance.k_id_bicycle
	IS 'Identificador único de la bicicleta a la que se le realizó el mantenimiento. Este valor hace referencia directa a la bicicleta registrada en el sistema y permite asociar cada intervención con un elemento físico específico de la flota. Al ser de tipo VARCHAR, admite codificación que diferencia bicicletas eléctricas y mecánicas, mejorando el control operativo y la trazabilidad del historial técnico.'
;





COMMENT ON TABLE panic_button
	IS 'Esta tabla se encarga de almacenar todos los registros de activaciones del botón de pánico en cada estación. Su propósito es tener un historial detallado de cada vez que el botón es activado, lo que permite un seguimiento adecuado de los incidentes de emergencia y su respuesta.'
;



COMMENT ON TABLE slots
	IS 'La tabla slots representa los espacios físicos disponibles en una estación para asegurar una bicicleta dentro del sistema de movilidad. Cada slot corresponde a un punto de anclaje equipado con un candado electrónico (padlock) que permite verificar su estado y asociarlo tanto a una bicicleta como a una estación específica. Esta tabla permite gestionar la ocupación, disponibilidad y estado operativo de cada espacio de estacionamiento.'
;

COMMENT ON COLUMN slots.k_id_slot
	IS 'Identificador único del slot dentro del sistema. Es la llave primaria de la tabla y permite distinguir de manera inequívoca cada punto de anclaje disponible en una estación.'
;

COMMENT ON COLUMN slots.t_padlock_status
	IS 'Indica el estado actual del candado electrónico asociado al slot. Usualmente representa valores como abierto, cerrado, bloqueado, fallo, entre otros. Es un campo clave para determinar si un slot está disponible para recibir una bicicleta o si requiere mantenimiento.'
;

COMMENT ON COLUMN slots.k_id_station
	IS 'Llave foránea que referencia a la estación a la que pertenece el slot. Permite relacionar cada punto de anclaje con una ubicación física específica dentro del sistema de estaciones.'
;

COMMENT ON TABLE station
	IS 'Tabla en la que se van a guardar los datos de la estaciones.'
;

COMMENT ON COLUMN station.k_id_station
	IS 'Llave primaria de la estacion.'
;

COMMENT ON COLUMN station.n_station_name
	IS 'Nombre de la estacion.'
;

COMMENT ON COLUMN station.n_latitude
	IS 'Latitud de la ubicacion exacta de la estacion.'
;

COMMENT ON COLUMN station.n_length
	IS 'Longitud de la ubicacion exacta de la estacion.'
;

COMMENT ON COLUMN station.k_id_city
	IS 'Llave foranea que vien desde ciudad.'
;

COMMENT ON COLUMN station.t_cctv_status
	IS 'Es el campo encargado de dar verificacion si el CCTV esta activo y funcional'
;



COMMENT ON TABLE travel
	IS 'Esta es la tabla en la que se van a guardar todos los viajes.'
;

COMMENT ON COLUMN travel.k_id_travel
	IS 'Llave primaria del viaje.'
;

COMMENT ON COLUMN travel.f_required_at
	IS 'Entidad encargada de guardar la fecha de solitud de viaje.'
;

COMMENT ON COLUMN travel.f_started_at
	IS 'Fecha de inicio del viaje.'
;

COMMENT ON COLUMN travel.f_ended_at
	IS 'Fecha de finalizacion del viaje'
;

COMMENT ON COLUMN travel.t_status
	IS 'Estado del viaje'
;

COMMENT ON COLUMN travel.k_id_bicycle
	IS 'Llave foranea de Bicycle'
;

COMMENT ON COLUMN travel.k_from_id_station
	IS 'Llave foranea de la estacion de donde se inicio el viaje.'
;

COMMENT ON COLUMN travel.k_to_id_station
	IS 'Llave Foranea de la estacion en donde se termina el viaje'
;



COMMENT ON TABLE user_fine
	IS 'En esta tabla se van a guardar todas las multas de los usuarios.'
;

COMMENT ON COLUMN user_fine.k_user_fine
	IS 'Llave primaria de la tabla de rompimiento entre user y fine.'
;

COMMENT ON COLUMN user_fine.n_reason
	IS 'Razon por la cual le pusieron la multa al usuario.'
;

COMMENT ON COLUMN user_fine.t_state
	IS 'Estado de la multa que se le puso al usuario.'
;

COMMENT ON COLUMN user_fine.k_id_fine
	IS 'Llave foranea de fine(multa)'
;

COMMENT ON COLUMN user_fine.k_uid_user
	IS 'Llave foranea de user(usuario)'
;

COMMENT ON COLUMN user_fine.v_amount_snapshot
	IS 'Valor que tuvo la multa en el momento en que se la colocaron.'
;

COMMENT ON COLUMN user_fine.f_assigned_at
	IS 'Fecha en la que fue asignada la multa.'
;

COMMENT ON COLUMN user_fine.f_update_at
	IS 'Fecha en la que fue actualizada la multa.'
;



COMMENT ON TABLE users
	IS 'Tabla que guarda todos los datos de los usuarios.'
;

COMMENT ON COLUMN users.k_uid_user
	IS 'Llave primaria de user(Usuarios) que entrega el servidor de autenticacion.'
;

COMMENT ON COLUMN users.n_user_name
	IS 'Primer nombre del usuario.'
;

COMMENT ON COLUMN users.t_subscription_type
	IS 'Tipo de suscripcion del usuario.'
;

COMMENT ON COLUMN users.v_balance
	IS 'Saldo de los usuario'
;


-- Roles principales
CREATE ROLE manager_users LOGIN PASSWORD 'g_user';
CREATE ROLE manager_bicycle LOGIN PASSWORD 'g_bicy';
CREATE ROLE manager_travel LOGIN PASSWORD 'g_travel';
CREATE ROLE manager_admins LOGIN PASSWORD 'g_admin';
CREATE ROLE manager_fine LOGIN PASSWORD 'g_fine';
CREATE ROLE manager_station LOGIN PASSWORD 'g_station';
CREATE ROLE manager_city LOGIN PASSWORD 'g_city';
CREATE ROLE manager_slots LOGIN PASSWORD 'g_slots';
CREATE ROLE manager_maintenance LOGIN PASSWORD 'g_maintenance';
CREATE ROLE manager_complaints LOGIN PASSWORD 'g_complaints';
CREATE ROLE manager_btnpanic LOGIN PASSWORD 'g_btnpanic';

-- Privilegios sobre tablas
GRANT SELECT, INSERT, UPDATE, DELETE ON public.users TO manager_users;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.bicycle TO manager_bicycle;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.admins TO manager_admins;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.city  TO manager_city;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO manager_city;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.station TO manager_station;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fine TO manager_fine;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE public.fine_k_id_fine_seq TO manager_fine;


GRANT SELECT, INSERT, UPDATE, DELETE ON public.travel TO manager_travel;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO manager_travel;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_fine TO manager_fine;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE public.user_fine_k_user_fine_seq TO manager_fine;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.complaints_and_claims TO manager_complaints;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE public.complaints_and_claims_k_id_complaints_and_claims_seq TO manager_complaints;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.panic_button TO manager_btnpanic;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE public.panic_button_k_id_panic_button_seq TO manager_btnpanic;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.slots TO manager_slots;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.maintenance TO manager_maintenance;
