"""Initial migration

Revision ID: ba985c44b6bc
Revises: 
Create Date: 2025-11-04 02:37:44.568912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba985c44b6bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bicycles',
    sa.Column('idBicileta', sa.Integer(), nullable=False),
    sa.Column('serie', sa.String(), nullable=True),
    sa.Column('modelo', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('idBicileta'),
    schema='bicycle'
    )
    op.create_index(op.f('ix_bicycle_bicycles_idBicileta'), 'bicycles', ['idBicileta'], unique=False, schema='bicycle')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bicycle_bicycles_idBicileta'), table_name='bicycles', schema='bicycle')
    op.drop_table('bicycles', schema='bicycle')
    # ### end Alembic commands ###
