-- Crear bases de datos adicionales
CREATE DATABASE movilidad_sostenible;
CREATE DATABASE keycloak;

\connect movilidad_sostenible;


/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 15-nov.-2025 11:28:42 p. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */















/* Drop Tables */

DROP TABLE IF EXISTS admins CASCADE
;

DROP TABLE IF EXISTS bicycle CASCADE
;

DROP TABLE IF EXISTS city CASCADE
;

DROP TABLE IF EXISTS email_verification CASCADE
;

DROP TABLE IF EXISTS fine CASCADE
;

DROP TABLE IF EXISTS payment_method CASCADE
;

DROP TABLE IF EXISTS station CASCADE
;

DROP TABLE IF EXISTS travel CASCADE
;

DROP TABLE IF EXISTS user_fine CASCADE
;

DROP TABLE IF EXISTS users CASCADE
;

/* Create Tables */

CREATE TABLE admins
(
	k_admin_cc varchar(11) NOT NULL,	-- Cedula de ciudadania del adminitrador y llave primaria de la tabla administrador.
	n_first_name varchar(50) NOT NULL,	-- Primer nombre del administrador.
	n_second_name varchar(50) NULL,	-- Segundo nombre del administrador.
	n_first_lastname varchar(50) NOT NULL,	-- Primer apellido del administrador.
	n_second_lastname varchar(50) NULL,	-- Segundo apellido del administrador.
	f_admin_birthday date NOT NULL,	-- Fecha de nacimiento del administrador.
	n_admin_email varchar(100) NOT NULL,	-- Correo electronico del administrador.
	f_admin_registration_date date NOT NULL	-- Fecha de registro del usuario en la aplicacion.
)
;

CREATE TABLE bicycle
(
	k_id_bicycle serial NOT NULL,	-- Llave primaria de la bicicleta.
	k_series integer NOT NULL,	-- Serie de la bicicleta.
	n_model varchar(50) NOT NULL,	-- Modelo de la bicicleta.
	t_padlock_status varchar(50) NOT NULL   DEFAULT 'CLOSE',	-- Estado del candado de la bicicleta.
	f_last_update timestamp without time zone NULL,	-- Ultima actualizacion de la bicicleta.
	n_latitude double precision NULL,	-- Latitud de la posicion de la bicicleta.
	n_length double precision NULL,	-- Longitud de la posicion de la bicicleta.
	v_battery numeric(5,2) NULL,	-- Bbateria de la bicicleta.
	k_current_id_station integer NOT NULL
)
;

CREATE TABLE city
(
	k_id_city serial NOT NULL,	-- Llave primaria de la ciudad.
	n_city_name varchar(50) NULL	-- Nombre de la ciudad.
)
;

CREATE TABLE email_verification
(
	k_id_email_verification serial NOT NULL,
	n_otp_hash varchar(255) NOT NULL,
	f_expires_at timestamp without time zone NOT NULL,
	t_consumed boolean NOT NULL   DEFAULT false,
	f_created_at timestamp without time zone NOT NULL   DEFAULT NOW(),
	k_user_cc integer NOT NULL
)
;

CREATE TABLE fine
(
	k_id_fine serial NOT NULL,
	v_amount numeric(9) NULL
)
;

CREATE TABLE payment_method
(
	k_id_payment_method varchar(10) NOT NULL,
	t_card_type varchar(10) NOT NULL,
	v_number varchar(16) NOT NULL,
	f_expiration_date date NOT NULL,
	n_owner_name varchar(50) NOT NULL,
	v_balance numeric(9) NULL,
	k_user_cc integer NOT NULL
)
;

CREATE TABLE station
(
	k_id_station serial NOT NULL,	-- Llave primaria de la estacion.
	n_station_name varchar(50) NOT NULL,	-- Nombre de la estacion.
	d_street varchar(40) NULL,	-- Callede la direccion de la estacion.
	d_avenue varchar(40) NULL,	-- Carrera de la direccion de la estacion.
	d_number varchar(40) NULL,	-- Numero de la direccion de la estacion
	k_id_city integer NOT NULL	-- Llave foranea que vien desde ciudad.
)
;

CREATE TABLE travel
(
	k_id_travel serial NOT NULL,	-- Llave primaria del viaje.
	f_started_at timestamp without time zone NOT NULL   DEFAULT NOW(),	-- Fecha de solicitud del viaje.
	f_ended_at timestamp without time zone NULL,
	t_status varchar(20) NOT NULL,
	k_user_cc integer NOT NULL,	-- Llave foranea de user
	k_id_bicycle integer NOT NULL,	-- Llave foranea de Bicycle
	k_from_id_station integer NOT NULL,
	k_to_id_station integer NULL
)
;

CREATE TABLE user_fine
(
	k_user_fine serial NOT NULL,
	n_reason varchar(250) NOT NULL,
	t_state varchar(50) NOT NULL   DEFAULT 'PENDING',
	k_id_multa integer NOT NULL,
	k_user_cc integer NOT NULL
)
;

CREATE TABLE users
(
	k_user_cc integer NOT NULL,	-- Cedula de ciudadania del ususario y llave primaria de la tabla usuario.
	n_username varchar(50) NOT NULL,
	n_hashed_password varchar(255) NOT NULL,
	n_user_first_name varchar(50) NOT NULL,	-- Primer nombre del usuario.
	n_user_second_name varchar(50) NULL,	-- Segundo nombre del usuario.
	n_user_first_lastname varchar(50) NOT NULL,	-- Primer apellido del ususario.
	n_user_second_lastname varchar(50) NULL,	-- Segundo apellido del usuario.
	f_user_birthdate date NOT NULL,	-- Fecha de nacimiento del usuario.
	n_user_email varchar(100) NOT NULL,	-- Correo electronico del usuario.
	t_subscription_type varchar(50) NOT NULL   DEFAULT 'NONE',	-- Tipo de suscripcion del usuario.
	f_user_registration_date date NOT NULL,	-- Fecha de registro del usuario en la aplicacion.
	t_is_verified boolean NOT NULL   DEFAULT false	-- Es el atrivuto que indicara si el usuario completo su registro verificando su cuenta
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE admins ADD CONSTRAINT "PK_admins"
	PRIMARY KEY (k_admin_cc)
;

ALTER TABLE admins
  ADD CONSTRAINT "UNQ_n_admin_email" UNIQUE (n_admin_email)
;

ALTER TABLE bicycle ADD CONSTRAINT "PK_Bicycle"
	PRIMARY KEY (k_id_bicycle)
;

ALTER TABLE bicycle
  ADD CONSTRAINT "UNQ_k_series" UNIQUE (k_series)
;

ALTER TABLE bicycle ADD CONSTRAINT "CHK_v_battery" CHECK (v_battery BETWEEN 0 AND 100)
;

ALTER TABLE bicycle ADD CONSTRAINT "CHK_t_padlock_status" CHECK (t_padlock_status IN ('CLOSE', 'OPEN'))
;

CREATE INDEX "IXFK_bicycle_station" ON bicycle (k_current_id_station ASC)
;

ALTER TABLE city ADD CONSTRAINT "PK_city"
	PRIMARY KEY (k_id_city)
;

ALTER TABLE city
  ADD CONSTRAINT "UNQ_n_city_name" UNIQUE (n_city_name)
;

ALTER TABLE email_verification ADD CONSTRAINT "PK_email_verification"
	PRIMARY KEY (k_id_email_verification)
;

ALTER TABLE email_verification
  ADD CONSTRAINT "UNQ_k_user_cc" UNIQUE (k_user_cc)
;

CREATE INDEX "IXFK_email_verification_users" ON email_verification (k_user_cc ASC)
;

CREATE INDEX "IXFK_email_verification_users_02" ON email_verification (k_user_cc ASC)
;

ALTER TABLE fine ADD CONSTRAINT "PK_Fine"
	PRIMARY KEY (k_id_fine)
;

ALTER TABLE payment_method ADD CONSTRAINT "PK_Payment_method"
	PRIMARY KEY (k_id_payment_method)
;

CREATE INDEX "IXFK_Payment_method_User" ON payment_method (k_user_cc ASC)
;

ALTER TABLE station ADD CONSTRAINT "PK_Station"
	PRIMARY KEY (k_id_station)
;

CREATE INDEX "IXFK_Station_City" ON station (k_id_city ASC)
;

ALTER TABLE travel ADD CONSTRAINT "PK_Travel"
	PRIMARY KEY (k_id_travel)
;

ALTER TABLE travel ADD CONSTRAINT "CK_Travel_status" CHECK (t_status IN ('REQUIRED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'))
;

CREATE INDEX "IXFK_travel_bicycle" ON travel (k_id_bicycle ASC)
;

CREATE INDEX "IXFK_travel_station" ON travel (k_from_id_station ASC)
;

CREATE INDEX "IXFK_travel_station_02" ON travel (k_to_id_station ASC)
;

CREATE INDEX "IXFK_travel_users" ON travel (k_user_cc ASC)
;

ALTER TABLE user_fine ADD CONSTRAINT "PK_User_fine"
	PRIMARY KEY (k_user_fine)
;

ALTER TABLE user_fine ADD CONSTRAINT "CHK_t_state" CHECK (t_state IN ('PENDING', 'PAID'))
;

CREATE INDEX "IXFK_User_fine_Fine" ON user_fine (k_id_multa ASC)
;

CREATE INDEX "IXFK_User_fine_User" ON user_fine (k_user_cc ASC)
;

ALTER TABLE users ADD CONSTRAINT "PK_Users"
	PRIMARY KEY (k_user_cc)
;

ALTER TABLE users
  ADD CONSTRAINT "UNQ_n_user_email" UNIQUE (n_user_email)
;

ALTER TABLE users
  ADD CONSTRAINT "UNQ_n_username" UNIQUE (n_username)
;

ALTER TABLE users ADD CONSTRAINT "CHK_t_subscription_type" CHECK (t_subscription_type IN ('NONE', 'MONTHLY')
)
;

/* Create Foreign Key Constraints */

ALTER TABLE bicycle ADD CONSTRAINT "FK_bicycle_station"
	FOREIGN KEY (k_current_id_station) REFERENCES station (k_id_station) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE email_verification ADD CONSTRAINT "FK_email_verification_users"
	FOREIGN KEY (k_user_cc) REFERENCES users (k_user_cc) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE email_verification ADD CONSTRAINT "FK_email_verification_users_02"
	FOREIGN KEY (k_user_cc) REFERENCES users (k_user_cc) ON DELETE Cascade ON UPDATE No Action
;

ALTER TABLE payment_method ADD CONSTRAINT "FK_Payment_method_User"
	FOREIGN KEY (k_user_cc) REFERENCES users (k_user_cc) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE station ADD CONSTRAINT "FK_Station_City"
	FOREIGN KEY (k_id_city) REFERENCES city (k_id_city) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE travel ADD CONSTRAINT "FK_travel_bicycle"
	FOREIGN KEY (k_id_bicycle) REFERENCES bicycle (k_id_bicycle) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE travel ADD CONSTRAINT "FK_travel_station"
	FOREIGN KEY (k_from_id_station) REFERENCES station (k_id_station) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE travel ADD CONSTRAINT "FK_travel_station_02"
	FOREIGN KEY (k_to_id_station) REFERENCES station (k_id_station) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE travel ADD CONSTRAINT "FK_travel_users"
	FOREIGN KEY (k_user_cc) REFERENCES users (k_user_cc) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE user_fine ADD CONSTRAINT "FK_User_fine_Fine"
	FOREIGN KEY (k_id_multa) REFERENCES fine (k_id_fine) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE user_fine ADD CONSTRAINT "FK_User_fine_User"
	FOREIGN KEY (k_user_cc) REFERENCES users (k_user_cc) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE admins
	IS 'Tabla que guarda todos los datos de los adminitradores.'
;

COMMENT ON COLUMN admins.k_admin_cc
	IS 'Cedula de ciudadania del adminitrador y llave primaria de la tabla administrador.'
;

COMMENT ON COLUMN admins.n_first_name
	IS 'Primer nombre del administrador.'
;

COMMENT ON COLUMN admins.n_second_name
	IS 'Segundo nombre del administrador.'
;

COMMENT ON COLUMN admins.n_first_lastname
	IS 'Primer apellido del administrador.'
;

COMMENT ON COLUMN admins.n_second_lastname
	IS 'Segundo apellido del administrador.'
;

COMMENT ON COLUMN admins.f_admin_birthday
	IS 'Fecha de nacimiento del administrador.'
;

COMMENT ON COLUMN admins.n_admin_email
	IS 'Correo electronico del administrador.'
;

COMMENT ON COLUMN admins.f_admin_registration_date
	IS 'Fecha de registro del usuario en la aplicacion.'
;

COMMENT ON TABLE bicycle
	IS 'Esta es la tabla en la que se guardan los datos de las bicicletas.'
;

COMMENT ON COLUMN bicycle.k_id_bicycle
	IS 'Llave primaria de la bicicleta.'
;

COMMENT ON COLUMN bicycle.k_series
	IS 'Serie de la bicicleta.'
;

COMMENT ON COLUMN bicycle.n_model
	IS 'Modelo de la bicicleta.'
;

COMMENT ON COLUMN bicycle.t_padlock_status
	IS 'Estado del candado de la bicicleta.'
;

COMMENT ON COLUMN bicycle.f_last_update
	IS 'Ultima actualizacion de la bicicleta.'
;

COMMENT ON COLUMN bicycle.n_latitude
	IS 'Latitud de la posicion de la bicicleta.'
;

COMMENT ON COLUMN bicycle.n_length
	IS 'Longitud de la posicion de la bicicleta.'
;

COMMENT ON COLUMN bicycle.v_battery
	IS 'Bbateria de la bicicleta.'
;



COMMENT ON TABLE city
	IS 'En esta tabla se van a guardar las ciudades.'
;

COMMENT ON COLUMN city.k_id_city
	IS 'Llave primaria de la ciudad.'
;

COMMENT ON COLUMN city.n_city_name
	IS 'Nombre de la ciudad.'
;







COMMENT ON TABLE payment_method
	IS 'Esta es la tabla encargada de guardar el metodo de pago del usuario.'
;

COMMENT ON TABLE station
	IS 'Tabla en la que se van a guardar los datos de la estaciones.'
;

COMMENT ON COLUMN station.k_id_station
	IS 'Llave primaria de la estacion.'
;

COMMENT ON COLUMN station.n_station_name
	IS 'Nombre de la estacion.'
;

COMMENT ON COLUMN station.d_street
	IS 'Callede la direccion de la estacion.'
;

COMMENT ON COLUMN station.d_avenue
	IS 'Carrera de la direccion de la estacion.'
;

COMMENT ON COLUMN station.d_number
	IS 'Numero de la direccion de la estacion'
;

COMMENT ON COLUMN station.k_id_city
	IS 'Llave foranea que vien desde ciudad.'
;



COMMENT ON TABLE travel
	IS 'Esta es la tabla en la que se van a guardar todos los viajes.'
;

COMMENT ON COLUMN travel.k_id_travel
	IS 'Llave primaria del viaje.'
;

COMMENT ON COLUMN travel.f_started_at
	IS 'Fecha de solicitud del viaje.'
;

COMMENT ON COLUMN travel.k_user_cc
	IS 'Llave foranea de user '
;

COMMENT ON COLUMN travel.k_id_bicycle
	IS 'Llave foranea de Bicycle'
;



COMMENT ON TABLE user_fine
	IS 'En esta tabla se van a guardar todas las multas de los usuarios.'
;



COMMENT ON TABLE users
	IS 'Tabla que guarda todos los datos de los usuarios.'
;

COMMENT ON COLUMN users.k_user_cc
	IS 'Cedula de ciudadania del ususario y llave primaria de la tabla usuario.'
;

COMMENT ON COLUMN users.n_user_first_name
	IS 'Primer nombre del usuario.'
;

COMMENT ON COLUMN users.n_user_second_name
	IS 'Segundo nombre del usuario.'
;

COMMENT ON COLUMN users.n_user_first_lastname
	IS 'Primer apellido del ususario.'
;

COMMENT ON COLUMN users.n_user_second_lastname
	IS 'Segundo apellido del usuario.'
;

COMMENT ON COLUMN users.f_user_birthdate
	IS 'Fecha de nacimiento del usuario.'
;

COMMENT ON COLUMN users.n_user_email
	IS 'Correo electronico del usuario.'
;

COMMENT ON COLUMN users.t_subscription_type
	IS 'Tipo de suscripcion del usuario.'
;

COMMENT ON COLUMN users.f_user_registration_date
	IS 'Fecha de registro del usuario en la aplicacion.'
;

COMMENT ON COLUMN users.t_is_verified
	IS 'Es el atrivuto que indicara si el usuario completo su registro verificando su cuenta'
;
-- Roles principales
CREATE ROLE manager_users LOGIN PASSWORD 'g_user';
CREATE ROLE manager_bicycle LOGIN PASSWORD 'g_bicy';
CREATE ROLE manager_travel LOGIN PASSWORD 'g_travel';
CREATE ROLE manager_admins LOGIN PASSWORD 'g_admin';
CREATE ROLE manager_pay_method LOGIN PASSWORD 'g_pay_meth';
CREATE ROLE manager_fine LOGIN PASSWORD 'g_fine';
CREATE ROLE manager_user_fine LOGIN PASSWORD 'g_user_fine';
CREATE ROLE manager_station LOGIN PASSWORD 'g_station';
CREATE ROLE manager_city LOGIN PASSWORD 'g_city';
CREATE ROLE manager_email LOGIN PASSWORD 'g_email';

-- Privilegios sobre tablas
GRANT SELECT, INSERT, UPDATE, DELETE ON public.users TO manager_users;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.bicycle TO manager_bicycle;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.admins TO manager_admins;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.city  TO manager_city;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.station TO manager_station;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fine TO manager_fine;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.payment_method TO manager_pay_method;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.travel TO manager_travel;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO manager_travel;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_fine TO manager_user_fine;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.email_verification TO manager_email;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO manager_email;