/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 31-oct.-2025 8:16:31 p. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

/* Drop Tables */

DROP TABLE IF EXISTS administrado CASCADE
;

DROP TABLE IF EXISTS bicicleta CASCADE
;

DROP TABLE IF EXISTS ciudad CASCADE
;

DROP TABLE IF EXISTS comienza_en CASCADE
;

DROP TABLE IF EXISTS estacion CASCADE
;

DROP TABLE IF EXISTS finaliza_en CASCADE
;

DROP TABLE IF EXISTS metodo_pago CASCADE
;

DROP TABLE IF EXISTS multa CASCADE
;

DROP TABLE IF EXISTS usuario CASCADE
;

DROP TABLE IF EXISTS usuario_multa CASCADE
;

DROP TABLE IF EXISTS viaje CASCADE
;

/* Create Tables */

CREATE TABLE administrado
(
	k_cedula_ciudadania_administrador varchar(11) NOT NULL,	-- Cedula de ciudadania del adminitrador y llave primaria de la tabla administrador.
	n_primer_nombre varchar(50) NOT NULL,	-- Primer nombre del administrador.
	n_segundo_nombre varchar(50) NULL,	-- Segundo nombre del administrador.
	n_primer_apellido varchar(50) NOT NULL,	-- Primer apellido del administrador.
	n_segundo_apellido varchar(50) NULL,	-- Segundo apellido del administrador.
	f_fecha_nacimiento date NOT NULL,	-- Fecha de nacimiento del administrador.
	n_correo_electronico varchar(100) NOT NULL,	-- Correo electronico del administrador.
	f_fecha_de_registro varchar(50) NOT NULL	-- Fecha de registro del usuario en la aplicacion.
)
;

CREATE TABLE bicicleta
(
	k_id_bicicleta serial NOT NULL,	-- Llave primaria de la bicicleta.
	k_serie serial NOT NULL,	-- Serie de la bicicleta.
	n_modelo varchar(50) NOT NULL,	-- Modelo de la bicicleta.
	t_estado_candado varchar(50) NOT NULL   DEFAULT 'CERRADO',	-- Estado del candado de la bicicleta.
	f_ultima_actualizacion timestamp without time zone NULL,	-- Ultima actualizacion de la bicicleta.
	n_latitud double precision NULL,	-- Latitud de la posicion de la bicicleta.
	n_longitud double precision NULL,	-- Longitud de la posicion de la bicicleta.
	v_bateria numeric(5,2) NULL	-- Bbateria de la bicicleta.
)
;

CREATE TABLE ciudad
(
	k_id_ciudad serial NOT NULL,	-- Llave primaria de la ciudad.
	n_nombre varchar(50) NULL	-- Nombre de la ciudad.
)
;

CREATE TABLE comienza_en
(
	f_fecha_inicio_viaje timestamp without time zone NOT NULL,	-- Fecha de inicio del viaje.
	k_id_viaje serial NOT NULL,
	k_id_estacion serial NOT NULL
)
;

CREATE TABLE estacion
(
	k_id_estacion serial NOT NULL,	-- Llave primaria de la estacion.
	n_nombre varchar(50) NULL,	-- Nombre de la estacion.
	d_calle varchar(10) NULL,	-- Callede la direccion de la estacion.
	d_carrera varchar(10) NULL,	-- Carrera de la direccion de la estacion.
	d_numero varchar(10) NULL,	-- Numero de la direccion de la estacion
	k_id_ciudad serial NOT NULL	-- Llave foranea que vien desde ciudad.
)
;

CREATE TABLE finaliza_en
(
	f_fecha_finalizacion_viaje timestamp without time zone NOT NULL,	-- Fecha de finalizacion del viaje.
	k_id_viaje serial NOT NULL,	-- Llave foranea que vien desde viaje.
	k_id_estacion serial NOT NULL	-- Llave foranea que vien desde estacion.
)
;

CREATE TABLE metodo_pago
(
	k_id_metodo_pago varchar(10) NOT NULL,
	t_tipo_tarjeta varchar(10) NOT NULL,
	v_numero varchar(16) NOT NULL,
	f_fecha_expiracion varchar(50) NOT NULL,
	n_nombre_titular varchar(50) NOT NULL,
	v_saldo numeric(9) NULL,
	k_cedula_ciudadania_usuario serial NOT NULL
)
;

CREATE TABLE multa
(
	k_id_multa serial NOT NULL,
	v_monto numeric(9) NULL
)
;

CREATE TABLE usuario
(
	k_cedula_ciudadania_usuario serial NOT NULL,	-- Cedula de ciudadania del ususario y llave primaria de la tabla usuario.
	n_usuario varchar(50) NOT NULL,
	n_contrasena varchar(50) NOT NULL,
	n_primer_nombre varchar(50) NOT NULL,	-- Primer nombre del usuario.
	n_segundo_nombre varchar(50) NULL,	-- Segundo nombre del usuario.
	n_primer_apellido varchar(50) NOT NULL,	-- Primer apellido del ususario.
	n_segundo_apellido varchar(50) NULL,	-- Segundo apellido del usuario.
	f_fecha_nacimiento date NOT NULL,	-- Fecha de nacimiento del usuario.
	n_correo_electronico varchar(100) NOT NULL,	-- Correo electronico del usuario.
	t_tipo_suscripcion varchar(50) NOT NULL   DEFAULT 'NINGUNA',	-- Tipo de suscripcion del usuario.
	f_fecha_de_registro varchar(50) NOT NULL	-- Fecha de registro del usuario en la aplicacion.
)
;

CREATE TABLE usuario_multa
(
	n_motivo varchar(250) NOT NULL,
	t_estado varchar(50) NOT NULL   DEFAULT 'PENDIENTE',
	k_id_multa serial NOT NULL,
	k_cedula_ciudadania_usuario serial NOT NULL
)
;

CREATE TABLE viaje
(
	k_id_viaje serial NOT NULL,	-- Llave primaria del viaje.
	f_fecha_solicitud timestamp without time zone NULL,	-- Fecha de solicitud del viaje.
	k_cedula_ciudadania_usuario serial NOT NULL,
	k_serie serial NOT NULL,
	k_id_bicicleta serial NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE administrado ADD CONSTRAINT "PK_administrado"
	PRIMARY KEY (k_cedula_ciudadania_administrador)
;

ALTER TABLE administrado 
  ADD CONSTRAINT "UNQ_n_correo_electronico_administrador" UNIQUE (n_correo_electronico)
;

ALTER TABLE bicicleta ADD CONSTRAINT "PK_Bicicleta"
	PRIMARY KEY (k_serie,k_id_bicicleta)
;

ALTER TABLE bicicleta ADD CONSTRAINT "CHK_v_bateria" CHECK (v_bateria BETWEEN 0 AND 100)
;

ALTER TABLE ciudad ADD CONSTRAINT "PK_ciudad"
	PRIMARY KEY (k_id_ciudad)
;

ALTER TABLE comienza_en ADD CONSTRAINT "PK_Comienza_en"
	PRIMARY KEY (k_id_estacion,k_id_viaje,f_fecha_inicio_viaje)
;

CREATE INDEX "IXFK_Comienza_en_Estacion" ON comienza_en (k_id_estacion ASC)
;

CREATE INDEX "IXFK_Comienza_en_Viaje" ON comienza_en (k_id_viaje ASC)
;

ALTER TABLE estacion ADD CONSTRAINT "PK_Estacion"
	PRIMARY KEY (k_id_estacion)
;

CREATE INDEX "IXFK_Estacion_Ciudad" ON estacion (k_id_ciudad ASC)
;

ALTER TABLE finaliza_en ADD CONSTRAINT "PK_Finaliza_en"
	PRIMARY KEY (f_fecha_finalizacion_viaje,k_id_viaje,k_id_estacion)
;

CREATE INDEX "IXFK_Finaliza_en_Estacion" ON finaliza_en (k_id_estacion ASC)
;

CREATE INDEX "IXFK_Finaliza_en_Viaje" ON finaliza_en (k_id_viaje ASC)
;

ALTER TABLE metodo_pago ADD CONSTRAINT "PK_Table3"
	PRIMARY KEY (k_id_metodo_pago,k_cedula_ciudadania_usuario)
;

ALTER TABLE metodo_pago ADD CONSTRAINT "CHK_f_fecha_expiracion" CHECK (f_fecha_expiracion ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'
)
;

CREATE INDEX "IXFK_Metodo_pago_Usuario" ON metodo_pago (k_cedula_ciudadania_usuario ASC)
;

ALTER TABLE multa ADD CONSTRAINT "PK_Multa"
	PRIMARY KEY (k_id_multa)
;

ALTER TABLE usuario ADD CONSTRAINT "PK_Usuario"
	PRIMARY KEY (k_cedula_ciudadania_usuario)
;

ALTER TABLE usuario 
  ADD CONSTRAINT "UNQ_n_correo_electronico_usuario" UNIQUE (n_correo_electronico)
;

ALTER TABLE usuario 
  ADD CONSTRAINT "UNQ_n_usuario" UNIQUE (n_usuario)
;

ALTER TABLE usuario ADD CONSTRAINT "CHK_t_tipo_suscripcion" CHECK (t_tipo_suscripcion IN ('NINGUNA', 'MENSUAL')
)
;

ALTER TABLE usuario_multa ADD CONSTRAINT "PK_Usuario_multa"
	PRIMARY KEY (k_cedula_ciudadania_usuario,k_id_multa,n_motivo,t_estado)
;

ALTER TABLE usuario_multa ADD CONSTRAINT "CHK_t_estado" CHECK (t_estado IN ('PENDIENTE', 'PAGADA'))
;

CREATE INDEX "IXFK_Usuario_multa_Multa" ON usuario_multa (k_id_multa ASC)
;

CREATE INDEX "IXFK_Usuario_multa_Usuario" ON usuario_multa (k_cedula_ciudadania_usuario ASC)
;

ALTER TABLE viaje ADD CONSTRAINT "PK_viaje"
	PRIMARY KEY (k_id_viaje)
;

CREATE INDEX "IXFK_Viaje_bicicleta" ON viaje (k_serie ASC,k_id_bicicleta ASC)
;

CREATE INDEX "IXFK_Viaje_Usuario" ON viaje (k_cedula_ciudadania_usuario ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE estacion ADD CONSTRAINT "FK_Estacion_Ciudad"
	FOREIGN KEY (k_id_ciudad) REFERENCES ciudad (k_id_ciudad) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE finaliza_en ADD CONSTRAINT "FK_Finaliza_en_Estacion"
	FOREIGN KEY (k_id_estacion) REFERENCES estacion (k_id_estacion) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE finaliza_en ADD CONSTRAINT "FK_Finaliza_en_Viaje"
	FOREIGN KEY (k_id_viaje) REFERENCES viaje (k_id_viaje) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE metodo_pago ADD CONSTRAINT "FK_Metodo_pago_Usuario"
	FOREIGN KEY (k_cedula_ciudadania_usuario) REFERENCES usuario (k_cedula_ciudadania_usuario) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE usuario_multa ADD CONSTRAINT "FK_Usuario_multa_Multa"
	FOREIGN KEY (k_id_multa) REFERENCES multa (k_id_multa) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE usuario_multa ADD CONSTRAINT "FK_Usuario_multa_Usuario"
	FOREIGN KEY (k_cedula_ciudadania_usuario) REFERENCES usuario (k_cedula_ciudadania_usuario) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE administrado
	IS 'Tabla que guarda todos los datos de los adminitradores.'
;

COMMENT ON COLUMN administrado.k_cedula_ciudadania_administrador
	IS 'Cedula de ciudadania del adminitrador y llave primaria de la tabla administrador.'
;

COMMENT ON COLUMN administrado.n_primer_nombre
	IS 'Primer nombre del administrador.'
;

COMMENT ON COLUMN administrado.n_segundo_nombre
	IS 'Segundo nombre del administrador.'
;

COMMENT ON COLUMN administrado.n_primer_apellido
	IS 'Primer apellido del administrador.'
;

COMMENT ON COLUMN administrado.n_segundo_apellido
	IS 'Segundo apellido del administrador.'
;

COMMENT ON COLUMN administrado.f_fecha_nacimiento
	IS 'Fecha de nacimiento del administrador.'
;

COMMENT ON COLUMN administrado.n_correo_electronico
	IS 'Correo electronico del administrador.'
;

COMMENT ON COLUMN administrado.f_fecha_de_registro
	IS 'Fecha de registro del usuario en la aplicacion.'
;

COMMENT ON TABLE bicicleta
	IS 'Esta es la tabla en la que se guardan los datos de las bicicletas.'
;

COMMENT ON COLUMN bicicleta.k_id_bicicleta
	IS 'Llave primaria de la bicicleta.'
;

COMMENT ON COLUMN bicicleta.k_serie
	IS 'Serie de la bicicleta.'
;

COMMENT ON COLUMN bicicleta.n_modelo
	IS 'Modelo de la bicicleta.'
;

COMMENT ON COLUMN bicicleta.t_estado_candado
	IS 'Estado del candado de la bicicleta.'
;

COMMENT ON COLUMN bicicleta.f_ultima_actualizacion
	IS 'Ultima actualizacion de la bicicleta.'
;

COMMENT ON COLUMN bicicleta.n_latitud
	IS 'Latitud de la posicion de la bicicleta.'
;

COMMENT ON COLUMN bicicleta.n_longitud
	IS 'Longitud de la posicion de la bicicleta.'
;

COMMENT ON COLUMN bicicleta.v_bateria
	IS 'Bbateria de la bicicleta.'
;

 

 

COMMENT ON TABLE ciudad
	IS 'En esta tabla se van a guardar las ciudades.'
;

COMMENT ON COLUMN ciudad.k_id_ciudad
	IS 'Llave primaria de la ciudad.'
;

COMMENT ON COLUMN ciudad.n_nombre
	IS 'Nombre de la ciudad.'
;

 

COMMENT ON TABLE comienza_en
	IS 'Tabla en la que se van a guardar los datos de inicio del viaje.'
;

COMMENT ON COLUMN comienza_en.f_fecha_inicio_viaje
	IS 'Fecha de inicio del viaje.'
;

 

 

COMMENT ON TABLE estacion
	IS 'Tabla en la que se van a guardar los datos de la estaciones.'
;

COMMENT ON COLUMN estacion.k_id_estacion
	IS 'Llave primaria de la estacion.'
;

COMMENT ON COLUMN estacion.n_nombre
	IS 'Nombre de la estacion.'
;

COMMENT ON COLUMN estacion.d_calle
	IS 'Callede la direccion de la estacion.'
;

COMMENT ON COLUMN estacion.d_carrera
	IS 'Carrera de la direccion de la estacion.'
;

COMMENT ON COLUMN estacion.d_numero
	IS 'Numero de la direccion de la estacion'
;

COMMENT ON COLUMN estacion.k_id_ciudad
	IS 'Llave foranea que vien desde ciudad.'
;

 

 

COMMENT ON TABLE finaliza_en
	IS 'Tabla en la que se van a guardar los datos de finalizacion del viaje.'
;

COMMENT ON COLUMN finaliza_en.f_fecha_finalizacion_viaje
	IS 'Fecha de finalizacion del viaje.'
;

COMMENT ON COLUMN finaliza_en.k_id_viaje
	IS 'Llave foranea que vien desde viaje.'
;

COMMENT ON COLUMN finaliza_en.k_id_estacion
	IS 'Llave foranea que vien desde estacion.'
;

 

 

COMMENT ON TABLE metodo_pago
	IS 'Esta es la tabla encargada de guardar el metodo de pago del usuario.'
;

 

 

COMMENT ON TABLE usuario
	IS 'Tabla que guarda todos los datos de los usuarios.'
;

COMMENT ON COLUMN usuario.k_cedula_ciudadania_usuario
	IS 'Cedula de ciudadania del ususario y llave primaria de la tabla usuario.'
;

COMMENT ON COLUMN usuario.n_primer_nombre
	IS 'Primer nombre del usuario.'
;

COMMENT ON COLUMN usuario.n_segundo_nombre
	IS 'Segundo nombre del usuario.'
;

COMMENT ON COLUMN usuario.n_primer_apellido
	IS 'Primer apellido del ususario.'
;

COMMENT ON COLUMN usuario.n_segundo_apellido
	IS 'Segundo apellido del usuario.'
;

COMMENT ON COLUMN usuario.f_fecha_nacimiento
	IS 'Fecha de nacimiento del usuario.'
;

COMMENT ON COLUMN usuario.n_correo_electronico
	IS 'Correo electronico del usuario.'
;

COMMENT ON COLUMN usuario.t_tipo_suscripcion
	IS 'Tipo de suscripcion del usuario.'
;

COMMENT ON COLUMN usuario.f_fecha_de_registro
	IS 'Fecha de registro del usuario en la aplicacion.'
;

 

COMMENT ON TABLE usuario_multa
	IS 'En esta tabla se van a guardar todas las multas de los usuarios.'
;

 

 

COMMENT ON TABLE viaje
	IS 'Esta es la tabla en la que se van a guardar todos los viajes.'
;

COMMENT ON COLUMN viaje.k_id_viaje
	IS 'Llave primaria del viaje.'
;

COMMENT ON COLUMN viaje.f_fecha_solicitud
	IS 'Fecha de solicitud del viaje.'
;

 

 

 

 
