-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.administrador
(
    k_cedula_ciudadania_administrador character varying(11) COLLATE pg_catalog."default" NOT NULL,
    n_primer_nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    n_segundo_nombre character varying(50) COLLATE pg_catalog."default",
    n_primer_apellido character varying(50) COLLATE pg_catalog."default" NOT NULL,
    n_segundo_apellido character varying(50) COLLATE pg_catalog."default",
    f_fecha_nacimiento date NOT NULL,
    n_correo_electronico character varying(100) COLLATE pg_catalog."default" NOT NULL,
    n_cargo character varying(15) COLLATE pg_catalog."default" NOT NULL,
    PRIMARY KEY (k_cedula_ciudadania_administrador),
    CONSTRAINT administrador_k_cc_key UNIQUE (k_cedula_ciudadania_administrador),
    CONSTRAINT "administrador_n_correoElectronico_key" UNIQUE (n_correo_electronico)
);

CREATE TABLE IF NOT EXISTS public.bicicleta
(
    k_id_bicicleta character varying(10) COLLATE pg_catalog."default" NOT NULL,
    k_serie character varying(10) COLLATE pg_catalog."default" NOT NULL,
    n_modelo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    t_estado_candado character varying(25) COLLATE pg_catalog."default" NOT NULL,
    f_tiempo_actualizacion timestamp with time zone[],
    n_latitud character varying(50),
    n_longitud character varying(50),
    v_bateria smallint,
    PRIMARY KEY (k_id_bicicleta),
    CONSTRAINT bicicleta_k_serie_key UNIQUE (k_serie)
);

CREATE TABLE IF NOT EXISTS public.ciudad
(
    k_id_ciudad character varying(10) COLLATE pg_catalog."default" NOT NULL,
    n_nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    PRIMARY KEY (k_id_ciudad),
    CONSTRAINT ciudad_n_nombre_key UNIQUE (n_nombre)
);

CREATE TABLE IF NOT EXISTS public."comienzaEn"
(
    k_id_viaje character varying(10) COLLATE pg_catalog."default" NOT NULL,
    k_id_estacion character varying(10) COLLATE pg_catalog."default" NOT NULL,
    f_fecha timestamp with time zone NOT NULL,
    PRIMARY KEY (k_id_viaje, k_id_estacion, f_fecha)
);

CREATE TABLE IF NOT EXISTS public.estacion
(
    k_id_estacion character varying(10) COLLATE pg_catalog."default" NOT NULL,
    n_nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    d_calle character varying(10) COLLATE pg_catalog."default" NOT NULL,
    d_carrera character varying(10) COLLATE pg_catalog."default" NOT NULL,
    d_numero character varying(10) COLLATE pg_catalog."default" NOT NULL,
    "k_idCiudad" character varying(10) COLLATE pg_catalog."default" NOT NULL,
    PRIMARY KEY (k_id_estacion),
    CONSTRAINT estacion_n_nombre_key UNIQUE (n_nombre)
);

CREATE TABLE IF NOT EXISTS public."metodoPago"
(
    k_id_metodo_pago character varying(10) COLLATE pg_catalog."default" NOT NULL,
    k_cedula_ciudadania_usuario character varying(11) COLLATE pg_catalog."default" NOT NULL,
    t_tipo_tarjeta character varying(10) COLLATE pg_catalog."default" NOT NULL,
    v_numero character varying(16) COLLATE pg_catalog."default" NOT NULL,
    f_fecha_expiracion date NOT NULL,
    n_nombre_titular character varying(100) COLLATE pg_catalog."default" NOT NULL,
    v_saldo bigint NOT NULL,
    PRIMARY KEY (k_id_metodo_pago),
    CONSTRAINT "metodoPago_k_CCUsuario_key" UNIQUE (k_cedula_ciudadania_usuario),
    CONSTRAINT "metodoPago_n_nombreTitular_key" UNIQUE (n_nombre_titular),
    CONSTRAINT "metodoPago_v_numero_key" UNIQUE (v_numero)
);

CREATE TABLE IF NOT EXISTS public.multas
(
    k_id_multa character varying(10) COLLATE pg_catalog."default" NOT NULL,
    v_monto bigint NOT NULL,
    n_motivo character varying(250) COLLATE pg_catalog."default" NOT NULL,
    t_estado character varying(15) COLLATE pg_catalog."default" NOT NULL,
    f_fecha_emision date NOT NULL,
    PRIMARY KEY (k_id_multa)
);

CREATE TABLE IF NOT EXISTS public."teriminaEn"
(
    k_id_viaje character varying(10) COLLATE pg_catalog."default" NOT NULL,
    k_id_estacion character varying(10) COLLATE pg_catalog."default" NOT NULL,
    f_fecha timestamp with time zone NOT NULL,
    PRIMARY KEY (k_id_viaje, k_id_estacion, f_fecha)
);

CREATE TABLE IF NOT EXISTS public.usuario
(
    k_cedula_ciudadania_usuario character varying(11) COLLATE pg_catalog."default" NOT NULL,
    n_primer_nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    n_segundo_nombre character varying(50) COLLATE pg_catalog."default",
    n_primer_apellido character varying(50) COLLATE pg_catalog."default" NOT NULL,
    n_segundo_apellido character varying(50) COLLATE pg_catalog."default",
    f_fecha_nacimiento date NOT NULL,
    n_correo_electronico character varying(100) COLLATE pg_catalog."default" NOT NULL,
    t_tipo_suscripcion character varying(50) COLLATE pg_catalog."default" NOT NULL,
    f_fecha_registro date NOT NULL,
    PRIMARY KEY (k_cedula_ciudadania_usuario),
    CONSTRAINT "usuario_n_correoElectronico_key" UNIQUE (n_correo_electronico)
);

CREATE TABLE IF NOT EXISTS public.viaje
(
    k_id_viaje character varying(10) COLLATE pg_catalog."default" NOT NULL,
    f_fecha_solicitud timestamp with time zone NOT NULL,
    k_cedula_ciudadania_usuario character varying(11) COLLATE pg_catalog."default" NOT NULL,
    k_id_bicicleta character varying(10) COLLATE pg_catalog."default" NOT NULL,
    PRIMARY KEY (k_id_viaje)
);

CREATE TABLE IF NOT EXISTS public.usuario_multa
(
    k_id_multa character varying(10) COLLATE pg_catalog."default" NOT NULL,
    k_cedula_ciudadania_usuario character varying(11) COLLATE pg_catalog."default" NOT NULL,
    n_motivo character varying(250) COLLATE pg_catalog."default" NOT NULL,
    t_estado character varying(15) COLLATE pg_catalog."default" NOT NULL,
    "f_fechaEmision" date NOT NULL,
    PRIMARY KEY (k_id_multa, k_cedula_ciudadania_usuario)
);

ALTER TABLE IF EXISTS public."comienzaEn"
    ADD CONSTRAINT "comienzaEn_fk0" FOREIGN KEY (k_id_viaje)
    REFERENCES public.viaje (k_id_viaje) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "comienzaEn_k_idViaje_key"
    ON public."comienzaEn"(k_id_viaje);


ALTER TABLE IF EXISTS public."comienzaEn"
    ADD CONSTRAINT "comienzaEn_fk1" FOREIGN KEY (k_id_estacion)
    REFERENCES public.estacion (k_id_estacion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "comienzaEn_k_idEstacion_key"
    ON public."comienzaEn"(k_id_estacion);


ALTER TABLE IF EXISTS public.estacion
    ADD CONSTRAINT estacion_fk5 FOREIGN KEY ("k_idCiudad")
    REFERENCES public.ciudad (k_id_ciudad) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."metodoPago"
    ADD CONSTRAINT "metodoPago_fk6" FOREIGN KEY (k_cedula_ciudadania_usuario)
    REFERENCES public.usuario (k_cedula_ciudadania_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "metodoPago_k_CCUsuario_key"
    ON public."metodoPago"(k_cedula_ciudadania_usuario);


ALTER TABLE IF EXISTS public."teriminaEn"
    ADD CONSTRAINT "teriminaEn_fk0" FOREIGN KEY (k_id_viaje)
    REFERENCES public.viaje (k_id_viaje) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "teriminaEn_k_idViaje_key"
    ON public."teriminaEn"(k_id_viaje);


ALTER TABLE IF EXISTS public."teriminaEn"
    ADD CONSTRAINT "teriminaEn_fk1" FOREIGN KEY (k_id_estacion)
    REFERENCES public.estacion (k_id_estacion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "teriminaEn_k_idEstacion_key"
    ON public."teriminaEn"(k_id_estacion);


ALTER TABLE IF EXISTS public.viaje
    ADD CONSTRAINT viaje_fk2 FOREIGN KEY (k_cedula_ciudadania_usuario)
    REFERENCES public.usuario (k_cedula_ciudadania_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.viaje
    ADD CONSTRAINT viaje_fk3 FOREIGN KEY (k_id_bicicleta)
    REFERENCES public.bicicleta (k_id_bicicleta) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.usuario_multa
    ADD CONSTRAINT "Fky_multa" FOREIGN KEY (k_id_multa)
    REFERENCES public.multas (k_id_multa) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.usuario_multa
    ADD CONSTRAINT "Fky" FOREIGN KEY (k_cedula_ciudadania_usuario)
    REFERENCES public.usuario (k_cedula_ciudadania_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;